### ISSUE TITLE
Release 4.5.0 checklist

### ISSUE THREAD

**Issue by rahulporuri** [enthought/apptools#105]
- [x] Review open PRs
- [x] Review open issues for anything else that should go into this release.
- [x] Update changelog
- [x] Make release branch
- [x] Bump version on release branch (via PR against release branch)
- [x] Bump version on master for continued development
- [x] Testing! (Create sdist, install from sdist, check tests pass.)
- [x] Tag
- [x] Testing!
- [x] Update release information on GitHub
- [x] PyPI upload
- [x] More testing!
- [ ] Build and upload documentation.
- [x] Buildsystem issue for package update
- [x] ~Bring any necessary changes back into master~ Nothing to do.

---

After eggs are built for EDM:

- [ ] One more round of testing with the EDM eggs
- [ ] Announce the release (Slack, portal, ets-users)

**Comment by rahulporuri** [comment]
closing as the release was made and the eggs were uploaded (a long long time back)
